### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by deadcoder0904** [SaraVieira/letslearngraphql.com#1]
https://github.com/SaraVieira/letslearngraphql.com/blob/5da16c601e4862468f8049e23e69aa2c7b802416/src/Components/Form.js#L204

`me an` -> `me and`

lol I'm a grammar police 😂

**Comment by SaraVieira** [comment]
🤦🏽‍♂️Grammar is hard :(

Mind making a PR?

**Comment by deadcoder0904** [comment]
No problem :)
